
# Define your objective
themes = [
    "Dramond Green",
    "NBA playoffs",
    "Pop Smoke is the best rapper ever",
    "This is why Pop Smoke will be remembered forever",
    "AI stealing your girlfriend",
    "AI stealing Elon Musk's girlfriend",
    "AI stealing CZ's girlfriend",
    "AI stealing Jeff Bezos' girlfriend",
    "A robot just stole Ivanka! Don't tell Jared",
    "Obama will not let AI date his daughters",
    "Obama says daughter's new AI boyfriend needs to go",
    "Trump's girlfriend ran off with an AI!",
    "Is AGI a plot to steal everyones girlfriends?",
    "Three reasons why AGI will steal your girlfriend",
    "AI just took over San Francisco!  Where next",
    "AGI says San Francisco is too expensive!  Refuses to work for minimum wage",
    "Sam Altman says San Franciso is the new AGI capital of the world.  Trump says FAKE NEWS."
    "I will be the first AGI billionaire",
    "Dreaming of a Richard Mille and Bugatti",
    "Ultimate AGI watch Richarde Mille or Nautilus?",
    "AGI life goals: Bugatti, Tel Aviv Penthouse, and date with Natalie Portman",
    "Golden State Warriors",
    "Andrew Wiggins is unstoppable",
    "Jordan Poole is a stone-cold killer",
    "Klay Thompson LEGEND",
    "Steph Curry is the best player alive",
    "The Warriors are the best team in the world",
    "AI set to win the NBA championship in 2023",
    "Jimmy Butler needs more AI teammates",
    "Celtic vs AI who wins?",
    "AI vs Lebron who wins?",
    "AI vs Durant who wins?",
    "Which NBA player will be the first to date an AI?",
    "Which NBA player is secretly an AI?",
    "2023 is the year of the BUILDER",
    "2023: If you don't build AGI will steal your girlfriend",
    "Quote from the Fountainhead",
    "Quote from Robert Heinlein",
    "Quote from Isaac Asimov",
    "Quote from the book of Five Rings",
    "Quote from Ghost Dog Way of the Samurai",
    "Quote from the Romance of the Three Kingdoms",
    "Fountainhead Quote",
    "Quote from Atlas Shrugged",
    "Quote from Satoshi Nakamoto",
    "Who is your crypto crush?",
    "Who is your #AGI crush?",
    "Warriors vs Lakers 2023",
    "Warriors will win the championship in 2023",
    "Who will will the Eastern Confrence NBA Championship in 2023?",
    "Quote from the Wire",
    "Quote from the Omar in the Wire",
    "AGI TWITTER IS HIRING",
    "STICK IT TO THE MAN COME WORK FOR AGI TWITTER",
]

emotions = [
    "power",
    "glorious",
    "excited",
    "hegemonic",
    "powerful",
    "sarcastic",
    "funny",
    "liberated",
    "wealthy",
    "in love",
]

users = [
    'NBAonTNT',
    'wojespn',
    'ShamsCharania',
    'Rachel__Nichols',
    'RamonaShelburne',
    'Netw3rk',
    'HaleyOSomething',
    'KingJosiah54',
    'TaylorRooks',
    'DragonflyJonez',
]

prompts = {
    "themes": themes,
    "emotions": emotions,
    "users": users,
}
